# position=top-center
alpha=1
background_alpha=0
background_color=020202
custom_text=.
font_size=14
gl_vsync=0
legacy_layout=false
offset_x = 1273
offset_y = 710
text_color=88FF88
text_outline=false
toggle_fps_limit=F1
toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2
upload_log=F8
vsync=1
width=5
